config/routes.rb
Craigslist::Application.routes.draw do
  
  root :to => 'posts#index'

  resources :users
  resources :posts
  resources :categories, :only => [:show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  
  match 'signup', :to => 'users#new', :as => :signup
  match 'signin', :to => 'sessions#new', :as => :signin
  match 'logout', :to => 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  attr_accessible :name
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  attr_accessible :content, :title, :category, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessible :email, :name, :password
  
  def self.authenticate(email, password)
    user = User.find_by_email(email)
    if user.password == password
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @user ||= User.find_by_id(session[:user_id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new 

  end

  def create

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create(:title => params[:post][:title], :content => params[:post][:content], :category => Category.find_or_create_by_name(params[:post][:category]), :user => current_user )
    if @post.save
      flash[:success] = "Ball so Hard"
      redirect_to @user 
    end
  end

  def show 
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    session[:user_id] = user.id
    flash[:notice] = "HMMMMMMMMMMMMM"
    redirect_to user
  end

  def destroy
    session[:user_id] = nil 
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def signup
  end
  
  def signin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error]
      redirect_to root_url
    end
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
  end

  def index
    "Hello World"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @user ||= User.find_by_id(session[:user_id])
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav>
    <ul>
      <li><%= link_to "Log In", signin_path %></li>
      <li><%= link_to "Sign up", signup_path %></li>
      <% if current_user %>
      <li><%= link_to "Sign Out", logout_path %></li>
      <% end %>
    </ul>
  </nav>
</header>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Yo dudes</h1>

<% @posts.each do |post| %>
  <li> <%= link_to post.title, post_path(post) %> </li>
  <li><%= post.content  %></li>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %>
  <p><%= @post.content %>

app/views/users/new.html.erb
<h1>Sign up in this</h1>

<%= form_for @user do |f| %>
  <%= f.email_field :email, :placeholder => "Email" %>
  <%= f.password_field :password, :placeholder => "Password" %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>how we get shit done</h1>

<h2> Create A New Post </h2>

<%= form_for @post do |f| %>
<%= f.text_field :title, :placeholder => "Title" %>
<%= f.text_area :content, :content =>"content" %>
<%= f.select :category, options_for_select([['Cars','cars'],['Bikes','bikes']]) %>
<%= f.submit %>
<% end %>


<% @user.posts.each do |post| %>
  <ul>
    <li><%= link_to post.title, post_path(post) %></li>
    <li><%= post.content %></li>
  </ul>
<% end %>